# Generated by Django 3.1.2 on 2020-11-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201102_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ('path', models.CharField(default='', max_length=255)),
                ('method', models.CharField(default='', max_length=255)),
                (
                    'execution_time', models.CharField(
                        default='', max_length=255
                    )
                ),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
