# Generated by Django 3.1.2 on 2020-11-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_logger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
