# Generated by Django 3.1.2 on 2020-11-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201105_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
