# Generated by Django 3.1.2 on 2020-11-02 11:20

from django.db import migrations

import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201102_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=phone_field.models.PhoneField(
                blank=True,
                help_text='Contact phone number',
                max_length=31
            ),
        ),
    ]
