# Generated by Django 3.1.2 on 2020-11-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201109_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='experience',
            field=models.PositiveSmallIntegerField(choices=[(0, 'TRAINEE'), (1, 'JUNIOR'), (2, 'MIDDLE'), (3, 'SENIOR')], default=0),
        ),
    ]
