# Generated by Django 3.1.2 on 2020-11-09 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201109_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lastname',
        ),
    ]
