# Generated by Django 3.1.2 on 2020-11-02 00:15

from django.db import migrations


def capitalize_student_name(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    student_temp = apps.get_model('core', 'Student')
    for student in student_temp.objects.all():
        student.firstname = student.firstname.capitalize()
        student.lastname = student.lastname.capitalize()
        student.save()


def capitalize_teacher_name(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    teacher_temp = apps.get_model('core', 'Teacher')
    for teacher in teacher_temp.objects.all():
        teacher.firstname = teacher.firstname.capitalize()
        teacher.lastname = teacher.lastname.capitalize()
        teacher.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201102_0013'),
    ]

    operations = [
        migrations.RunPython(capitalize_student_name),
        migrations.RunPython(capitalize_teacher_name)
    ]
