# Generated by Django 3.1.2 on 2020-11-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20201110_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                (
                    'currency_name',
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 'USD'),
                            (2, 'EUR'),
                            (3, 'RUR')
                        ]
                    )
                ),
                (
                    'currency_buy_rate',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10
                    )
                ),
                (
                    'currency_sell_rate',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10
                    )
                ),
                (
                    'currency_rate_date',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),
                (
                    'bank',
                    models.CharField(
                        max_length=30
                    )
                ),
            ],
        ),
    ]
