# Generated by Django 3.1.2 on 2020-11-02 00:13
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201102_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='core.teacher',
                verbose_name='Учитель'
            ),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(
                on_delete=models.SET('Without Group'),
                related_name='students',
                to='core.group',
                verbose_name='Группа'
            ),
        ),
    ]
